language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
script: echo override build
# install coverage dependencies
install:
  - pip install codecov
  - pip install coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
